name: GuessTheNumber
version: 1.1.1
api: [2.0.0]
main: SalmonDE\Number
description: Adds a nice guessing game to your server!
author: SalmonDE
website: https://salmonde.de/
commands:
 guessgame:
  description: Starts a guessing game!
  permission: guessthenumber.normal
 guessgamesquare:
  description: Starts a harder guessing game!
  permission: guessthenumber.square
 guessgamesolution:
  description: Shows the player the solution of the current task
  permission: guessthenumber.solution
 guessgameabort:
  description: Aborts a guessing game
  permission: guessthenumber.abort
permissions:
 guessthenumber:
  description: Main permission of GuessTheNumber
  children:
   guessthenumber.normal:
    description: Permission to use /guessgame
   guessthenumber.square:
    description: Permission /guessgamesquare
   guessthenumber.solution:
    description: Allows the user of the command to see the wanted number of the guessing game
   guessthenumber.abort:
    description: Permission to abort a guessing game
