name: GuessTheNumber
version: 2.0.0
api: 2.0.0
main: SalmonDE\Number
description: Guessing Game for your Server!
author: SalmonDE
website: https://salmonde.de/
commands:
 guessgame:
  description: Starts a Normal Guessing Game!
  permission: guessthenumber.normal
 guessgamesquare:
  description: Starts an Advanced Guessing Game!
  permission: guessthenumber.square
 guessgamesolution:
  description: Gives the user the solution to the current task.
  permission: guessthenumber.solution
 guessgameabort:
  description: Aborts the active guessing game.
  permission: guessthenumber.abort
permissions:
 guessthenumber:
  description: Main Permission Node
  children:
   guessthenumber.normal:
    description: Permission for "/guessgame"
   guessthenumber.square:
    description: Permission for "/guessgamesquare"
   guessthenumber.solution:
    description: Permission for "/guessgamesoluton"
   guessthenumber.abort:
    description: Permission for "/guessgameabort"
