name: GuessTheNumber
version: 1.0.0
api: [2.0.0]
main: SalmonDE\Number
description: Adds a nice guessing game to your server!
author: SalmonDE
website: https://salmonde.de/
commands:
 guess:
  description: Starts a guessing game!
  permission: guessthenumber.normal
 guessquare:
  description: Starts a harder guessing game!
  permission: guessthenumber.square
permissions:
 guessthenumber:
  description: Main permission of GuessTheNumber
  children:
   guessthenumber.normal:
    description: Permission to use /guess
   guessthenumber.square:
    description: Permission /guessquare
   guessthenumber.solution:
    description: Allows the user of the command to see the wanted number of the guessing game