# Configuration file of GuessTheNumber!

# Languages available:
# eng (English), deu (Deutsch)
Language: eng
#
Minimum: 1
Maximum: 100
# Prize which the winner gets for a '/guessgame' quiz (normal)
Item: "265:0:10"
# Example: 265:0:10 // ID:Damage:Amount
# Prize which the winner gets for a '/guessgamesquare' quiz (squares)
SquareItem: "322:0:1"

# Time which a player needs to wait until the plugins checks the answer in seconds
Timer: 5

# Report bugs here: https://github.com/SalmonCraftPE/GuessTheNumber/issues
# Have fun with this plugin! :)
# ~ SalmonDE