# Configuration file of GuessTheNumber!

# Languages available:
# deu (Deutsch)
Language: deu

# Min/Max Numbers for a normal guessing game
Min: 1
Max: 100

# Prize which the winner gets for a '/guessgame' quiz (normal)
# Example: 265:0:10 // ID:Damage:Amount
Item: '265:0:10'

# Prize which the winner gets for a '/guessgamesquare' quiz (squares)
SquareItem: '322:0:1'

# Time which a player needs to wait until the plugins checks the answer (In seconds)
Timer: 5

# Enable Auto Update?
Auto-Update: true
# Report bugs here: https://github.com/SalmonCraftPE/GuessTheNumber/issues/
# Have fun with this plugin! :)
# ~ SalmonDE
